# Generated by Django 4.2.15 on 2024-08-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='education_level',
        ),
    ]
