# Generated by Django 4.2.15 on 2024-08-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_department', models.TextField(max_length=200)),
                ('course_trainer', models.TextField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('course_status', models.CharField(default='active', max_length=30)),
                ('max_number_of_students', models.PositiveIntegerField(default=35)),
                ('course_level', models.CharField(max_length=30)),
            ],
        ),
    ]
