# Generated by Django 4.2.15 on 2024-08-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_code', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30)),
                ('bio', models.TextField()),
                ('guardian_name', models.CharField(max_length=40)),
                ('guardian_phone_number', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='')),
                ('courses', models.ManyToManyField(to='course.course')),
            ],
        ),
    ]
